displayName=Gnomeball
author=Tree Twunk
description=A plugin for organizing Gnomeball — a flag-football-style game using the OSRS gnome ball.
tags=game,event,gnomeball,gnome,ball,teams
plugins=gay.runescape.gnomeball.GnomeballPlugin